name: dartbag

# Description must be 60-180 characters to appease pub.dev's scoring system.
description: A grab-bag of miscellaneous, lightweight utility libraries for Dart.
version: 0.7.0-dev
repository: https://github.com/jamesderlin/dartbag

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  args: ^2.3.1
  clock: ^1.1.0
  collection: ^1.17.0
  matcher: ^0.12.14
  stack_trace: ^1.11.0

dev_dependencies:
  fake_async: ^1.3.0
  test: ^1.22.1
