name: dart_utils
description: Miscellaneous Dart utility code.
version: 0.1.15
publish_to: none

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  clock: ^1.1.0
  collection: ^1.16.0
  logging: ^1.0.2
  stack_trace: ^1.10.0

dev_dependencies:
  fake_async: ^1.3.0
  test: ^1.16.0
