name: dart_utils
description: Miscellaneous Dart utility code.
version: 0.1.14
publish_to: none

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  collection: ^1.16.0
  logging: ^1.0.2

dev_dependencies:
  test: ^1.16.0
