name: dartbag
description: A grab-bag of miscellaneous, lightweight utility code for Dart.
version: 0.2.1
repository: https://github.com/jamesderlin/dartbag

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  clock: ^1.1.0
  collection: ^1.16.0
  stack_trace: ^1.10.0

dev_dependencies:
  fake_async: ^1.3.0
  test: ^1.16.0
